

inline void* yimemcpy_sse2_asm(void* dest, const void* src, int size)
{
#ifndef __x64__
  asm volatile ("\n"
	"    leal      (%%esi, %0), %%ebx\n"
	"    cmp      $16, %%eax\n"
	"    jb	  normalcalc\n"
	"ssecalc:\n"
	"    movdqa   (%%esi),%%xmm0\n"
	"    leal      16(%%esi), %%esi \n"
	"    movdqa   %%xmm0,(%%edi)\n"
	"    leal      16(%%edi), %%edi\n"
	"    subl      $16, %%eax\n"
	"    cmp      $16, %%eax\n"
	"    jge      ssecalc\n"
	"    cmp      %%ebx, %%esi\n"
	"    je       end\n"
	"normalcalc:\n"
	"    cmp      $4, %%eax\n"
	"    jb       smalcalc\n"
	"    jz       end\n"
	"    movl     (%%esi), %%ecx\n"
	"    leal      4(%%esi), %%esi\n"
	"    movl     %%ecx, (%%edi)\n"
	"    lea      4(%%edi), %%edi\n"
	"    subl      $4, %%eax\n"
	"    jmp      normalcalc\n"
	"smalcalc:\n"
	"    movb      (%%esi), %%cl\n"
	"    leal      1(%%esi), %%esi\n"
	"    movb      %%cl, (%%edi)\n"
	"    leal      1(%%edi), %%edi\n"
	"    cmp      %%ebx, %%esi\n"
	"    jne      smalcalc\n"
	"end:\n"
	"    emms" :: "a" (size), "S" (src), "D" (dest) );
#else
  asm volatile ("\n"
	"    lea      (%%rsi, %0), %%rbx\n"
	"    cmp      $16, %%rax\n"
	"    jb	  normalcalc\n"
	"  ssecalc:\n"
	"    movdqa   (%%rsi),%%xmm0\n"
	"    lea      16(%%rsi), %%esi \n"
	"    movdqa   %%xmm0,(%%rdi)\n"
	"    lea      16(%%rdi), %%rdi\n"
	"    sub      $16, %%rax\n"
	"    cmp      $16, %%rax\n"
	"    jge      ssecalc\n"
	"    cmp      %%rbx, %%rsi\n"
	"    je       end\n"
	" normalcalc:\n"
	"    cmp      $4, %%eax\n"
	"    jb       smalcalc\n"
	"    jz       end\n"
	"    mov     (%%rsi), %%rcx\n"
	"    lea      4(%%rsi), %%rsi\n"
	"    mov     %%rcx, (%%rdi)\n"
	"    lea      4(%%rdi), %%rdi\n"
	"    sub      $4, %%rax\n"
	"    jmp      normalcalc\n"
	" smalcalc:\n"
	"    mov      (%%rsi), %%cl\n"
	"    lea      1(%%rsi), %%rsi\n"
	"    mov      %%cl, (%%rdi)\n"
	"    lea      1(%%rdi), %%rdi\n"
	"    cmp      %%rbx, %%rsi\n"
	"    jne      smalcalc\n"
	" end:\n"
	"    emms" :: "a" (size), "S" (src), "D" (dest):"rax", "rbx", "rcx");
#endif
	return dest;
}

