#pragma once

enum eResourceBitmapId {

	eRBID_FIXED_START=0,

	eRBID_CASHED_START = 256,
	eRBID_SHADOW_10,
	eRBID_SHADOW_2,
	eRBID_SHADOW_0,
	eRBID_SHAODW_1,
	eRBID_BTN_OK_INIT,
	eRBID_BTN_OK_DISABLE,
	eRBID_BTN_OK_PUSHED,
	eRBID_BTN_OK_MOUSE_IN,
	eRBID_BTN_CANCEL_INIT,
	eRBID_BTN_CANCEL_DISABLE,
	eRBID_BTN_CANCEL_PUSHED,
	eRBID_BTN_CANCEL_MOUSE_IN,
	eRBID_BTN_YES_INIT,
	eRBID_BTN_YES_DISABLE,
	eRBID_BTN_YES_PUSHED,
	eRBID_BTN_YES_MOUSE_IN,
	eRBID_BTN_NO_INIT,
	eRBID_BTN_NO_DISABLE,
	eRBID_BTN_NO_PUSHED,
	eRBID_BTN_NO_MOUSE_IN,
	eRBID_RADIO_ON,
	eRBID_RADIO_OFF,
};

enum eResourceTemporaryId {
	eRTID_BUTTON_FONT=1,
	eRTID_DIALOG_FONT,
	eRTID_DIALOG_CAPTION_FONT,
	eRTID_DEFAULT_FONT
};


#define DIALOG_SHADOW_WIDTH 10
#define DIALOG_SHADOW_WIDTH_OFF 2