//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GoYotsuya.rc
//
#define IDC_MYICON                      2
#define IDD_GOYOTSUYA_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_GOYOTSUYA                   107
#define IDI_SMALL                       108
#define IDC_GOYOTSUYA                   109
#define IDR_MAINFRAME                   128
#define IDD_REMOCON                     129
#define IDD_COMMENT_DIALOG              130
#define IDD_JOSEKI_DIALOG               131
#define IDC_R_PLAY                      1001
#define IDC_R_PLAY2                     1002
#define IDC_R_BACK                      1002
#define IDC_R_FF                        1003
#define IDC_R_RV                        1004
#define IDC_R_TOP                       1005
#define IDC_R_END                       1006
#define IDC_R_SHOW_NO                   1007
#define IDC_R_NEXT_BRANCH               1008
#define IDC_R_PREV_BRANCH               1009
#define IDC_R_NEXT_COMMENT              1010
#define IDC_R_NEXT_BRANCH2              1010
#define IDC_R_PASS                      1010
#define IDC_R_PREV_COMMENT              1011
#define IDC_R_MOUSE_MODE                1012
#define IDC_R_ADDSTONE_MODE             1012
#define IDC_R_DELETE_BRANCH             1013
#define IDC_EDIT1                       1014
#define IDC_COMMENT                     1014
#define IDC_INPUT_COMMENT               1014
#define IDC_R_SAVE_SGF                  1015
#define IDC_R_SAVE_YGF                  1016
#define IDC_R_HIDE_LABEL                1016
#define IDC_R_SAVE_YGF2                 1017
#define IDC_R_OPEN                      1017
#define IDC_R_HIDE_LABEL2               1017
#define IDC_R_QUIT_LABEL                1017
#define IDC_R_TEXT_OK                   1018
#define IDC_LABEL_SELECT                1019
#define IDC_R_SELECT_DEAD_STONE         1020
#define IDC_COMMENT_LIST                1020
#define IDC_LABEL_SELECT2               1020
#define IDC_CMB_HINDO                   1020
#define IDC_R_RESULT                    1021
#define IDC_LABEL_SELECT3               1021
#define IDC_CMB_NANIDO                  1021
#define IDC_INIT_STONE                  1022
#define IDC_INIT_STONE_COUNT            1022
#define IDC_TEXT_REGISTER               1022
#define IDC_LABEL_SELECT4               1022
#define IDC_CMB_STATUS                  1022
#define IDC_R_FREE_INITSTONE            1023
#define IDC_TEXT_REMOVE                 1023
#define IDC_CMB_TYPE                    1023
#define IDC_R_BLACK_DETAIL              1024
#define IDC_TEXT_REGISTER2              1024
#define IDC_TEXT_ADD                    1024
#define IDC_CMB_LABEL_SPETIAL           1024
#define IDC_R_BLACK_DETAIL2             1025
#define IDC_CMB_JOSEKI_NAME             1025
#define IDC_CMB_JOSEKI_NAME_HIGH        1025
#define IDC_R_BLACK_DETAIL3             1026
#define IDC_R_START_COMMENT             1027
#define IDC_CMB_STATUS3                 1027
#define IDC_JOSEKI_NAME_SMALL           1027
#define IDC_CMB_JOSEKI_NAME_LOW         1027
#define IDC_R_END_COMMENT               1028
#define IDC_LABEL_SELECT5               1028
#define IDC_CMB_STONE_VALUE             1028
#define IDC_R_INITSTONE                 1029
#define IDC_JOSEKI_NAME_DETAIL          1029
#define IDC_CMB_JOSEKI_NAME_DETAIL      1029
#define IDC_R_ADDSTONE_MODE2            1030
#define IDC_R_NORMAL_MODE               1030
#define IDC_R_OPEN2                     1031
#define IDC_R_OPEN_YGF                  1031
#define IDC_COMMENT_REGISTER            1032
#define IDC_R_SHOW_COMMENT              1033
#define IDC_CHECK_JOSEKI                1034
#define IDC_COMMENT_DELETE              1034
#define IDC_CHECK_JOSEKI2               1035
#define IDC_JOSEKI_REGISTER             1035
#define IDC_CHECK_JOSEKI3               1036
#define IDC_CHK_KIKI                    1036
#define IDC_CHECK_JOSEKI4               1037
#define IDC_CHK_EDIT_COMPLETE           1037
#define IDC_CHECK_JOSEKI5               1038
#define IDC_CHK_SICHO                   1038
#define IDC_CHECK_JOSEKI6               1039
#define IDC_CHK_OKIGO                   1039
#define IDC_CHECK_JOSEKI7               1040
#define IDC_CHK_SENTE                   1040
#define IDC_CHK_OKIGO2                  1040
#define IDC_CHK_OKINIIRI                1055
#define IDC_COMBO1                      1041
#define IDC_CMB_SUBJECT                 1041
#define IDC_COMBO2                      1042
#define IDC_CMB_TEXT                    1042
#define IDC_ADJUST                      1043
#define IDC_EDIT2                       1044
#define IDC_TXT_REGISTER                1044
#define IDC_COMMENT_CLEAR               1045
#define IDC_TXT_JOSEKI_REGISTER         1046
#define IDC_CMB_TEXT2                   1047
#define IDC_COMMENT_DELETE2             1048
#define IDC_TXT_REGISTER2               1049
#define IDC_COMMENT_REGISTER2           1050
#define IDC_LBL_JOSEKI_NAME             1051
#define IDC_R_OPTIMIZE                  1052
#define IDC_CMB_STONE_ATTR              1054
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
